---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: eic-pool-deployments
  namespace: mongodb-operator
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes:
      - SCRAM
  users:
  - name: admin-user
    db: admin
    passwordSecretRef:
      name: admin-user-secret
    roles:
    - name: clusterAdmin
      db: admin
    - name: userAdminAnyDatabase
      db: admin
    - name: restore
      db: admin
    - name: backup
      db: admin
    scramCredentialsSecretName: mongo-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          storageClassName: network-block
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 60Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-secret
  namespace: mongodb-operator
type: Opaque
stringData:
  password: idunEricss0n