global:
  iam:
    clientId: eo
    adminSecret: eric-sec-access-mgmt-creds
    userKey: kcadminid
    passwordKey: kcpasswd
  hosts:
    gr: ''
    gas: gas.212442621681.eu-west-1.ac.ericsson.se
    iam: iam.212442621681.eu-west-1.ac.ericsson.se
    pf: pf.212442621681.eu-west-1.ac.ericsson.se
    so: so.212442621681.eu-west-1.ac.ericsson.se
    uds: uds.212442621681.eu-west-1.ac.ericsson.se
  pullSecret: k8s-registry-secret
  registry:
    password: PASSWORD_REPLACE
    pullSecret: k8s-registry-secret
    url: armdocker.rnd.ericsson.se
    username: USERNAME_REPLACE
  support:
    ipv6:
      enabled: false
  timezone: UTC
  createClusterRoles: true
tags:
  pf: true
  so: true
  uds: true
  adc: false
  dmm: false
  th: false
  eas: false
  appmgr: true

eric-eo-api-gateway:
  iam:
    kubernetesSecret: eric-oss-common-base-iam-client-secret
eric-ctrl-bro:
  persistence:
    persistentVolumeClaim:
      size: 20Gi
  sftp:
    username: dummy
    password: dummy
eric-data-search-engine:
  service:
    network:
      protocol:
        IPv6: false

eric-eo-playbook-service:
  enabled: true

eric-eo-so:
  stubs:
    enabled: true
  defaultUser:
    password: IDUN_CRED_REPLACE
    username: so-user
eric-oss-pf:
  defaultUser:
    password: IDUN_CRED_REPLACE
    username: pf-user
eric-sec-access-mgmt:
  ingress:
    hostname: iam.212442621681.eu-west-1.ac.ericsson.se
  replicaCount: 2
gas:
  defaultUser:
    password: IDUN_CRED_REPLACE
    username: gas-user
system-user:
  credentials:
    password: IDUN_CRED_REPLACE
    username: sys-user
eric-oss-uds:
  defaultUser:
    password: IDUN_CRED_REPLACE
    username: uds-user

geo-redundancy:
  enabled: false
eric-gr-bur-orchestrator:
  credentials:
    username: ""
    password: ""
  gr:
    bro:
      autoDelete:
        backupsLimit: 10
    sftp:
      url: ""
      username: ""
      password: ""
    cluster:
      role: ""
      # note that the secondary_hostnames variable should only be defined if the role is set to "PRIMARY".
      # secondary_hostnames should be commented out if role is set to "SECONDARY".
      secondary_hostnames:
        - ""
    registry:
      secondarySiteContainerRegistryHostname:
