eric-oss-common-base:
  system-user:
    credentials:
      username: sys-user
      password: IDUN_CRED_REPLACE

  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: "100.85.163.134"
      annotations:
        # Cloud Provider(for ex. AWS):
        #  < Keys are to be placed in the cloudProviderLB hash. >
        cloudProviderLB:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ecn-subnet-2"
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "azeiapaasdev01-eiap-rg"
  gas:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 50Gi
    sftp:
      username: backupuser
      password: BACKUP_CRED_REPLACE

  eric-fh-snmp-alarm-provider:
    service:
      loadBalancerIP: "100.85.163.136"
      annotations:
        cloudProviderLB:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ecn-subnet-2"
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "azeiapaasdev01-eiap-rg"

eric-eo-so:
  stubs:
    enabled: false
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-oss-pf:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-oss-uds:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-oss-config-handling:
  cps-user:
    credentials:
      password: IDUN_CRED_REPLACE
  dmi-user:
    credentials:
      password: IDUN_CRED_REPLACE

eric-oss-oran-support:
  eric-oss-a1-policy-mngmt-svc:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-eo-playbook-service:
  enabled: true

eric-oss-ericsson-adaptation:
  eric-oss-ran-topology-adapter:
    rtaUser:
      password: IDUN_CRED_REPLACE

eric-oss-task-automation-ae:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-topology-handling:
  eric-oss-common-topology-svc:
    eric-oss-cmn-topology-svc-core:
      defaultUser:
        password: IDUN_CRED_REPLACE
