global:
  hosts:
    bdr: BDR_HOST_REPLACE
    eic: EIC_HOST_REPLACE
    iam: EIC_HOST_REPLACE
  eic:
    enabled: true
  bdr:
    enabled: true

eric-oss-common-base:
  system-user:
    credentials:
      username: sys-user
      password: IDUN_CRED_REPLACE
  eric-oss-ddc:
    autoUpload:
      enabled: true
      ddpid: lmi_stsvp1eic25
      account: lmi_stsvp1eic25@ddpi.athtem.eei.ericsson.se
      password: "_stsvp1eic25"

  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: "214.13.162.226"
      annotations:
        cloudProviderLB: {}

  gas:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-cloud-native-base:
  eric-odca-diagnostic-data-collector:
    sftpServerHost: "sftp-server:22"
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 50Gi
    sftp:
      username: backup
      password: BACKUP_CRED_REPLACE
  eric-data-object-storage-mn:
    openID:
      enabled: true
  eric-fh-snmp-alarm-provider:
    service:
      loadBalancerIP: "214.13.162.227"
      annotations:
        cloudProviderLB: {}

eric-oss-config-handling:
  cps-user:
    credentials:
      password: IDUN_CRED_REPLACE
  dmi-user:
    credentials:
      password: IDUN_CRED_REPLACE

eric-eo-playbook-service:
  enabled: true

eric-oss-oran-support:
  eric-oss-a1-policy-mngmt-svc:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-oss-ericsson-adaptation:
  eric-oss-ran-topology-adapter:
    rtaUser:
      password: IDUN_CRED_REPLACE

eric-oss-task-automation-ae:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-topology-handling:
  eric-oss-common-topology-svc:
    eric-oss-cmn-topology-svc-core:
      defaultUser:
        password: IDUN_CRED_REPLACE

eric-oss-app-mgr:
  eric-oss-app-onboarding:
    pythonJob:
      activeDeadlineSeconds: 3900
      ttlSecondsAfterFinished: 300
      pythonJobPollingTime: 4800

eric-service-exposure-framework:
  eric-sef-exposure-api-gateway:
    serviceMesh:
      ingress:
        hosts:
        - EIC_HOST_REPLACE

eric-cncs-oss-config:
  sef:
    enabled: true

eric-oss-dmm:
  eric-oss-dmm-kf-op-sz:
    kafka-cluster:
      kafka-listeners:
        oauthIngressTlsSecretName : eic-tls-secret