eric-oss-common-base:
  system-user:
    credentials:
      username: sys-user
      password: IDUN_CRED_REPLACE
  eric-oss-ddc:
    autoUpload:
      enabled: true
      ddpid: lmi_bmasidun01
      account: lmi_bmasidun01@ddpi.athtem.eei.ericsson.se
      password: "_bmasidun01"

  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: "10.10.10.10" # Dummy Value for AWS
      annotations:
        # Cloud Provider(for ex. AWS):
        #  < Keys are to be placed in the cloudProviderLB hash. >
        cloudProviderLB:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "100.65.22.35, 100.65.22.107"

  gas:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 50Gi
    sftp:
      username: backup
      password: BACKUP_CRED_REPLACE

  eric-fh-snmp-alarm-provider:
    service:
      loadBalancerIP: ""
      annotations:
        cloudProviderLB:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: udp
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "100.65.22.116, 100.65.22.21"

eric-eo-so:
  stubs:
    enabled: false
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-oss-pf:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-oss-uds:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-oss-config-handling:
  cps-user:
    credentials:
      password: IDUN_CRED_REPLACE
  dmi-user:
    credentials:
      password: IDUN_CRED_REPLACE

eric-oss-oran-support:
  eric-oss-a1-policy-mngmt-svc:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-eo-playbook-service:
  enabled: true

eric-oss-ericsson-adaptation:
  eric-oss-ran-topology-adapter:
    rtaUser:
      password: IDUN_CRED_REPLACE

eric-oss-task-automation-ae:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-topology-handling:
  eric-oss-common-topology-svc:
    eric-oss-cmn-topology-svc-core:
      defaultUser:
        password: IDUN_CRED_REPLACE

eric-oss-adc:
  eric-oss-enm-fns:
    ignoreSubscription: true
    configuredQueries: |-
      enms:
        - name: stsossflexcenm2000
          periodSeconds: 60
          queries:
            - name: query1
              topic: sftp-filetrans
              dmmDataTypeRegistrationParameters:
                dataSpace: "4G5G"
                dataCategory: PM_COUNTERS
              enmFileLookupServiceParameters:
                dataType: PM_STATISTICAL
                nodeType: "RadioNode"
                id: -1
              fileType: "xml.gz"
    dmm:
      dataCatalog:
        messageBusNamespace: "ossbmas01"
        messageBusName: "eric-oss-dmm-kf-op-sz-kafka-bootstrap"
  eric-oss-sftp-filetrans:
    sftp:
      topic_bucket_backward_compatible: false
    subsystem:
      name: "stsossflexcenm2000"
    dmm:
      enabled: true
      data_catalog:
        message_bus_name: "eric-oss-dmm-kf-op-sz-kafka-bootstrap"
        message_bus_namespace: "ossbmas01"
        data_provider_type_version_id: "stsossflexcenm2000"
        data_collector_name: "pm-counter-sftp-filetrans-stsossflexcenm2000"
        data_service:
          data_service_instance:
            consumed_data_provider: "stsossflexcenm2000"
    spring:
      kafka:
        auto:
          start: true
        topics:
          output:
            name: ran-pm-counter-sftp-file-transfer
          enm_id: "stsossflexcenm2000"
    connected:
      systems:
        enabled: true
  eric-oss-3gpp-pm-xml-ran-parser:
    bdr:
      enabled: true
    dmm:
      enabled: true
    connected:
      systems:
        enabled: true
    subsystem:
      name: "stsossflexcenm2000"
    file:
      util: "ran-pm-counter-sftp-file-transfer/"
    spring:
      kafka:
        topics:
          input:
            name: ran-pm-counter-sftp-file-transfer
          enm_id: "stsossflexcenm2000"
