eric-oss-common-base:
  system-user:
    credentials:
      username: sys-user
      password: IDUN_CRED_REPLACE
  eric-oss-ddc:
    autoUpload:
      enabled: true
      ddpid: lmi_stsvp1eic27
      account: lmi_stsvp1eic27@ddpi.athtem.eei.ericsson.se
      password: "_stsvp1eic27"

  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: "214.13.163.34"
      annotations:
        cloudProviderLB: {}

  gas:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-cloud-native-base:
  eric-odca-diagnostic-data-collector:
    sftpServerHost: "sftp-server:22"
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 50Gi
    sftp:
      username: backup
      password: BACKUP_CRED_REPLACE

  eric-fh-snmp-alarm-provider:
    service:
      loadBalancerIP: "214.13.163.35"
      annotations:
        cloudProviderLB: {}


eric-oss-config-handling:
  cps-user:
    credentials:
      password: IDUN_CRED_REPLACE
  dmi-user:
    credentials:
      password: IDUN_CRED_REPLACE

eric-eo-playbook-service:
  enabled: true

eric-oss-oran-support:
  eric-oss-a1-policy-mngmt-svc:
    defaultUser:
      password: IDUN_CRED_REPLACE

eric-oss-ericsson-adaptation:
  eric-oss-ran-topology-adapter:
    rtaUser:
      password: IDUN_CRED_REPLACE

eric-oss-task-automation-ae:
  defaultUser:
    password: IDUN_CRED_REPLACE

eric-topology-handling:
  eric-oss-common-topology-svc:
    eric-oss-cmn-topology-svc-core:
      defaultUser:
        password: IDUN_CRED_REPLACE

eric-oss-adc:
  eric-oss-enm-fns:
    ignoreSubscription: true
    configuredQueries: |-
      enms:
        - name: stsossflexcenm1011
          periodSeconds: 60
          queries:
            - name: query1
              topic: sftp-filetrans
              dmmDataTypeRegistrationParameters:
                dataSpace: "4G5G"
                dataCategory: PM_COUNTERS
              enmFileLookupServiceParameters:
                dataType: PM_STATISTICAL
                nodeType: "RadioNode"
                id: -1
              fileType: "xml.gz"
    dmm:
      dataCatalog:
        messageBusNamespace: "eric-eic"
        messageBusName: "eric-oss-dmm-kf-op-sz-kafka-bootstrap"
  eric-oss-sftp-filetrans:
    sftp:
      topic_bucket_backward_compatible: false
    subsystem:
      name: "stsossflexcenm1011"
    dmm:
      enabled: true
      data_catalog:
        message_bus_name: "eric-oss-dmm-kf-op-sz-kafka-bootstrap"
        message_bus_namespace: "eric-eic"
        data_provider_type_version_id: "stsossflexcenm1011"
        data_collector_name: "pm-counter-sftp-filetrans-stsossflexcenm1011"
        data_service:
          data_service_instance:
            consumed_data_provider: "stsossflexcenm1011"
    spring:
      kafka:
        auto:
          start: true
        topics:
          output:
            name: ran-pm-counter-sftp-file-transfer
          enm_id: "stsossflexcenm1011"
    connected:
      systems:
        enabled: true
  eric-oss-3gpp-pm-xml-ran-parser:
    bdr:
      enabled: true
    dmm:
      enabled: true
    connected:
      systems:
        enabled: true
    subsystem:
      name: "stsossflexcenm1011"
    file:
      util: "ran-pm-counter-sftp-file-transfer/"
    spring:
      kafka:
        topics:
          input:
            name: ran-pm-counter-sftp-file-transfer
          enm_id: "stsossflexcenm1011"
eric-oss-app-mgr:
  eric-oss-app-onboarding:
    pythonJob:
      activeDeadlineSeconds: 3900
      ttlSecondsAfterFinished: 300
      pythonJobPollingTime: 3600